### ISSUE TITLE
Local caching

### ISSUE THREAD

**Issue by MaximSpirin** [VerizonAdPlatforms/OneMobileSDK-releases-android#1]
Hello!
Is there any possible method of caching videos that are played by one mobile sdk?
Is there a way to select video quality?
Thanks!

**Comment by AleksanderLevadniy** [comment]
@MaximSpirin HI!

1. Yes, there is, I think we should discuss this in private
2. If content is in HLS, quality will adjust on fly, for non HLS content there is no way of doing this at the moment. If you are striving to have this feature we should discuss this in private.

Regards

**Comment by MarkGerl** [comment]
@MaximSpirin We look forward to talking to you more on Thursday in our meeting.

**Comment by AleksanderLevadniy** [comment]
@MaximSpirin @MarkGerl Can we now close this issue?
