### ISSUE TITLE
Unable to create oneSDK

### ISSUE THREAD

**Issue by mccartneym** [VerizonAdPlatforms/OneMobileSDK-releases-android#8]
Hi, 
I've been using the ReadMe doc to set up OneSDK (release 2.21). 

and am seeing `com.aol.mobile.sdk.player.http.HttpServiceException` from
OneSDKBuilder(context).create - onFailure callback

I'm stumped!

**Comment by MarkGerl** [comment]
You need to be an Oath Video Partner and have your App's Bundle ID registered to use the network.  What is the bundle ID you're using?

**Comment by mccartneym** [comment]
Thanks for getting back so quickly. I've just learning that for the moment we're not using Oath.
